//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinqia.CoreBank.Services.CUC.CadastroPessoa
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CucCluParametro", Namespace="http://schemas.datacontract.org/2004/07/CucCpwCadastros.Estruturas")]
    public partial class CucCluParametro : object
    {
        
        private int DependenciaField;
        
        private int EmpresaField;
        
        private string IPField;
        
        private string LoginField;
        
        private string SiglaAplicacaoField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dependencia
        {
            get
            {
                return this.DependenciaField;
            }
            set
            {
                this.DependenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiglaAplicacao
        {
            get
            {
                return this.SiglaAplicacaoField;
            }
            set
            {
                this.SiglaAplicacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CucCluRetorno", Namespace="http://schemas.datacontract.org/2004/07/CucCpwCadastros.Estruturas")]
    public partial class CucCluRetorno : object
    {
        
        private string CodigoContaRelacionamentoField;
        
        private string CodigoFilialField;
        
        private string CodigoPessoaField;
        
        private Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluExcecao ExcecaoField;
        
        private string TipoPessoaField;
        
        private string XmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoContaRelacionamento
        {
            get
            {
                return this.CodigoContaRelacionamentoField;
            }
            set
            {
                this.CodigoContaRelacionamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoFilial
        {
            get
            {
                return this.CodigoFilialField;
            }
            set
            {
                this.CodigoFilialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPessoa
        {
            get
            {
                return this.CodigoPessoaField;
            }
            set
            {
                this.CodigoPessoaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluExcecao Excecao
        {
            get
            {
                return this.ExcecaoField;
            }
            set
            {
                this.ExcecaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPessoa
        {
            get
            {
                return this.TipoPessoaField;
            }
            set
            {
                this.TipoPessoaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xml
        {
            get
            {
                return this.XmlField;
            }
            set
            {
                this.XmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CucCluExcecao", Namespace="http://schemas.datacontract.org/2004/07/CucCpwCadastros.Estruturas")]
    public partial class CucCluExcecao : object
    {
        
        private Sinqia.CoreBank.Services.CUC.CadastroPessoa.CategoriaExcecao CategoriaField;
        
        private long CodigoField;
        
        private string DetalheField;
        
        private string MensagemField;
        
        private string NomeColunaField;
        
        private string NomeTabelaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinqia.CoreBank.Services.CUC.CadastroPessoa.CategoriaExcecao Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalhe
        {
            get
            {
                return this.DetalheField;
            }
            set
            {
                this.DetalheField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeColuna
        {
            get
            {
                return this.NomeColunaField;
            }
            set
            {
                this.NomeColunaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTabela
        {
            get
            {
                return this.NomeTabelaField;
            }
            set
            {
                this.NomeTabelaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaExcecao", Namespace="http://schemas.datacontract.org/2004/07/CucCpwCadastros.Estruturas")]
    public enum CategoriaExcecao : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validacao = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CucCluParametroSimples", Namespace="http://schemas.datacontract.org/2004/07/CucCpwCadastros.Estruturas")]
    public partial class CucCluParametroSimples : object
    {
        
        private int DependenciaField;
        
        private int EmpresaField;
        
        private string IPField;
        
        private string LoginField;
        
        private string SenhaField;
        
        private string SiglaAplicacaoField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dependencia
        {
            get
            {
                return this.DependenciaField;
            }
            set
            {
                this.DependenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha
        {
            get
            {
                return this.SenhaField;
            }
            set
            {
                this.SenhaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiglaAplicacao
        {
            get
            {
                return this.SiglaAplicacaoField;
            }
            set
            {
                this.SiglaAplicacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sinqia.CoreBank.Services.CUC.CadastroPessoa.ICucCliCadastroPessoa")]
    public interface ICucCliCadastroPessoa
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/Atualizar", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/AtualizarResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> AtualizarAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaXmlAtualizacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/AtualizarSemToken", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/AtualizarSemTokenResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> AtualizarSemTokenAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametroSimples axobParametrosLogin, string axvaXmlAtualizacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/Excluir", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/ExcluirResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> ExcluirAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/ExcluirSemToken", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/ExcluirSemTokenResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> ExcluirSemTokenAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametroSimples axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/Selecionar", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/SelecionarResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> SelecionarAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/SelecionarSemToken", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/SelecionarSemTokenResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> SelecionarSemTokenAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametroSimples axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/SelecionarCabecalho", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/SelecionarCabecalhoResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> SelecionarCabecalhoAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/SelecionarCabecalhoSemToken", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/SelecionarCabecalhoSemTokenResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> SelecionarCabecalhoSemTokenAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametroSimples axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/VerificarExistencia", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/VerificarExistenciaResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> VerificarExistenciaAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaCpfCnpj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/VerificarExistenciaSemToken", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/VerificarExistenciaSemTokenResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> VerificarExistenciaSemTokenAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametroSimples axobParametrosLogin, string axvaCpfCnpj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/MigrarCadastro", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/MigrarCadastroResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> MigrarCadastroAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro aXobParametrosLogin, string aXvaXmlAtualizacao, string aXvaCodigoPessoaSimplificada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliCadastroPessoa/RecuperarPessoas", ReplyAction="http://tempuri.org/ICucCliCadastroPessoa/RecuperarPessoasResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> RecuperarPessoasAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaCpfCnpj, string axvaNomePessoa, string PageSkip, string PageTake);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ICucCliCadastroPessoaChannel : Sinqia.CoreBank.Services.CUC.CadastroPessoa.ICucCliCadastroPessoa, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class CucCliCadastroPessoaClient : System.ServiceModel.ClientBase<Sinqia.CoreBank.Services.CUC.CadastroPessoa.ICucCliCadastroPessoa>, Sinqia.CoreBank.Services.CUC.CadastroPessoa.ICucCliCadastroPessoa
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CucCliCadastroPessoaClient() : 
                base(CucCliCadastroPessoaClient.GetDefaultBinding(), CucCliCadastroPessoaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICucCliCadastroPessoa.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CucCliCadastroPessoaClient(EndpointConfiguration endpointConfiguration) : 
                base(CucCliCadastroPessoaClient.GetBindingForEndpoint(endpointConfiguration), CucCliCadastroPessoaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CucCliCadastroPessoaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CucCliCadastroPessoaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CucCliCadastroPessoaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CucCliCadastroPessoaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CucCliCadastroPessoaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> AtualizarAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaXmlAtualizacao)
        {
            return base.Channel.AtualizarAsync(axobParametrosLogin, axvaXmlAtualizacao);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> AtualizarSemTokenAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametroSimples axobParametrosLogin, string axvaXmlAtualizacao)
        {
            return base.Channel.AtualizarSemTokenAsync(axobParametrosLogin, axvaXmlAtualizacao);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> ExcluirAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial)
        {
            return base.Channel.ExcluirAsync(axobParametrosLogin, axvaCodigoPessoa, axvaCodigoFilial);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> ExcluirSemTokenAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametroSimples axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial)
        {
            return base.Channel.ExcluirSemTokenAsync(axobParametrosLogin, axvaCodigoPessoa, axvaCodigoFilial);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> SelecionarAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial)
        {
            return base.Channel.SelecionarAsync(axobParametrosLogin, axvaCodigoPessoa, axvaCodigoFilial);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> SelecionarSemTokenAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametroSimples axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial)
        {
            return base.Channel.SelecionarSemTokenAsync(axobParametrosLogin, axvaCodigoPessoa, axvaCodigoFilial);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> SelecionarCabecalhoAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial)
        {
            return base.Channel.SelecionarCabecalhoAsync(axobParametrosLogin, axvaCodigoPessoa, axvaCodigoFilial);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> SelecionarCabecalhoSemTokenAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametroSimples axobParametrosLogin, string axvaCodigoPessoa, string axvaCodigoFilial)
        {
            return base.Channel.SelecionarCabecalhoSemTokenAsync(axobParametrosLogin, axvaCodigoPessoa, axvaCodigoFilial);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> VerificarExistenciaAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaCpfCnpj)
        {
            return base.Channel.VerificarExistenciaAsync(axobParametrosLogin, axvaCpfCnpj);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> VerificarExistenciaSemTokenAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametroSimples axobParametrosLogin, string axvaCpfCnpj)
        {
            return base.Channel.VerificarExistenciaSemTokenAsync(axobParametrosLogin, axvaCpfCnpj);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> MigrarCadastroAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro aXobParametrosLogin, string aXvaXmlAtualizacao, string aXvaCodigoPessoaSimplificada)
        {
            return base.Channel.MigrarCadastroAsync(aXobParametrosLogin, aXvaXmlAtualizacao, aXvaCodigoPessoaSimplificada);
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluRetorno> RecuperarPessoasAsync(Sinqia.CoreBank.Services.CUC.CadastroPessoa.CucCluParametro axobParametrosLogin, string axvaCpfCnpj, string axvaNomePessoa, string PageSkip, string PageTake)
        {
            return base.Channel.RecuperarPessoasAsync(axobParametrosLogin, axvaCpfCnpj, axvaNomePessoa, PageSkip, PageTake);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICucCliCadastroPessoa))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICucCliCadastroPessoa))
            {
                return new System.ServiceModel.EndpointAddress("http://attbhzs021:83/PROD/Sites/FIN/CUCWCF/CucClwCadastroPessoa.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CucCliCadastroPessoaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICucCliCadastroPessoa);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CucCliCadastroPessoaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICucCliCadastroPessoa);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICucCliCadastroPessoa,
        }
    }
}
