//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinqia.CoreBank.Services.CUC.Autenticacao
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CucCluRetornoAutenticacao", Namespace="http://schemas.datacontract.org/2004/07/CucCpwCadastros.Estruturas")]
    public partial class CucCluRetornoAutenticacao : object
    {
        
        private Sinqia.CoreBank.Services.CUC.Autenticacao.CucCluExcecao ExcecaoField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinqia.CoreBank.Services.CUC.Autenticacao.CucCluExcecao Excecao
        {
            get
            {
                return this.ExcecaoField;
            }
            set
            {
                this.ExcecaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CucCluExcecao", Namespace="http://schemas.datacontract.org/2004/07/CucCpwCadastros.Estruturas")]
    public partial class CucCluExcecao : object
    {
        
        private Sinqia.CoreBank.Services.CUC.Autenticacao.CategoriaExcecao CategoriaField;
        
        private long CodigoField;
        
        private string DetalheField;
        
        private string MensagemField;
        
        private string NomeColunaField;
        
        private string NomeTabelaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinqia.CoreBank.Services.CUC.Autenticacao.CategoriaExcecao Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalhe
        {
            get
            {
                return this.DetalheField;
            }
            set
            {
                this.DetalheField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeColuna
        {
            get
            {
                return this.NomeColunaField;
            }
            set
            {
                this.NomeColunaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTabela
        {
            get
            {
                return this.NomeTabelaField;
            }
            set
            {
                this.NomeTabelaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaExcecao", Namespace="http://schemas.datacontract.org/2004/07/CucCpwCadastros.Estruturas")]
    public enum CategoriaExcecao : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validacao = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sinqia.CoreBank.Services.CUC.Autenticacao.ICucCliAutenticacao")]
    public interface ICucCliAutenticacao
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICucCliAutenticacao/Autenticar", ReplyAction="http://tempuri.org/ICucCliAutenticacao/AutenticarResponse")]
        System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.Autenticacao.CucCluRetornoAutenticacao> AutenticarAsync(string axvaUsuario, string axvaSenha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ICucCliAutenticacaoChannel : Sinqia.CoreBank.Services.CUC.Autenticacao.ICucCliAutenticacao, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class CucCliAutenticacaoClient : System.ServiceModel.ClientBase<Sinqia.CoreBank.Services.CUC.Autenticacao.ICucCliAutenticacao>, Sinqia.CoreBank.Services.CUC.Autenticacao.ICucCliAutenticacao
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CucCliAutenticacaoClient() : 
                base(CucCliAutenticacaoClient.GetDefaultBinding(), CucCliAutenticacaoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICucCliAutenticacao.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CucCliAutenticacaoClient(EndpointConfiguration endpointConfiguration) : 
                base(CucCliAutenticacaoClient.GetBindingForEndpoint(endpointConfiguration), CucCliAutenticacaoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CucCliAutenticacaoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CucCliAutenticacaoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CucCliAutenticacaoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CucCliAutenticacaoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CucCliAutenticacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Sinqia.CoreBank.Services.CUC.Autenticacao.CucCluRetornoAutenticacao> AutenticarAsync(string axvaUsuario, string axvaSenha)
        {
            return base.Channel.AutenticarAsync(axvaUsuario, axvaSenha);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICucCliAutenticacao))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICucCliAutenticacao))
            {
                return new System.ServiceModel.EndpointAddress("http://attbhzs021:83/PROD/Sites/FIN/CUCWCF/CucClwAutenticacao.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CucCliAutenticacaoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICucCliAutenticacao);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CucCliAutenticacaoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICucCliAutenticacao);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICucCliAutenticacao,
        }
    }
}
